version: '3.5'

services:

# Video bridge
    jvb2:
        image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable-7439}
        deploy:
                placement:
                        constraints: [node.hostname == ouyangjinhang.org]
        restart: ${RESTART_POLICY:-unless-stopped}
        ports:
             - target: ${JVB_PORT:-10001}
               published: ${JVB_PORT:-10001}
               protocol: udp
               mode: host
             - target: 8081
               published: ${JVB_COLIBRI_PORT:-8081}
               protocol: tcp
               mode: host
        configs:
            - source: my_config
              target: /defaults/jvb.conf
        environment:
            - DOCKER_HOST_ADDRESS
            - ENABLE_COLIBRI_WEBSOCKET
            - ENABLE_OCTO
            - ENABLE_MULTI_STREAM
            - JVB_RELAY_REGION
            - JVB_RELAY_ID
            - ENABLE_RELAY
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_DISABLE_STUN
            - JVB_PORT
            - JVB_MUC_NICKNAME
            - JVB_STUN_SERVERS
            - JVB_OCTO_BIND_ADDRESS
            - JVB_OCTO_PUBLIC_ADDRESS
            - JVB_OCTO_BIND_PORT
            - JVB_OCTO_REGION
            - JVB_WS_DOMAIN
            - JVB_WS_SERVER_ID
            - PUBLIC_URL
            - SENTRY_DSN="${JVB_SENTRY_DSN:-0}"
            - SENTRY_ENVIRONMENT
            - SENTRY_RELEASE
            - COLIBRI_REST_ENABLED
            - SHUTDOWN_REST_ENABLED
            - TZ
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - XMPP_PORT
        networks:
            my-overlay-network:
                 aliases:
                    - ${JVB_AUTH_USER}


    
configs:
   my_config:
         file: /home/ctyun/docker-jitsi-meet/jvb/rootfs/defaults/jvb.conf

# Custom network so all services can communicate using a FQDN
networks:
      my-overlay-network:
              external: true       
